# Generated by Django 6.0.3 on 2026-03-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='email',
        ),
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
