// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeuFnrA1TjDjiv3fVWZaLG5IcBqfGztuA',
    appId: '1:134783720891:web:6b7427d9a08ec1895a389e',
    messagingSenderId: '134783720891',
    projectId: 'fir-coneccion-1a529',
    authDomain: 'fir-coneccion-1a529.firebaseapp.com',
    storageBucket: 'fir-coneccion-1a529.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbvVD78S_K_A1ktCA6b39iwgKEoTEbOvo',
    appId: '1:134783720891:android:252a58e66008d1375a389e',
    messagingSenderId: '134783720891',
    projectId: 'fir-coneccion-1a529',
    storageBucket: 'fir-coneccion-1a529.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4E3NjkprpmIPgZnXdaE0Jw27QBcmx9U0',
    appId: '1:134783720891:ios:de07e23e39f6ca495a389e',
    messagingSenderId: '134783720891',
    projectId: 'fir-coneccion-1a529',
    storageBucket: 'fir-coneccion-1a529.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConeccion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4E3NjkprpmIPgZnXdaE0Jw27QBcmx9U0',
    appId: '1:134783720891:ios:de07e23e39f6ca495a389e',
    messagingSenderId: '134783720891',
    projectId: 'fir-coneccion-1a529',
    storageBucket: 'fir-coneccion-1a529.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConeccion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeuFnrA1TjDjiv3fVWZaLG5IcBqfGztuA',
    appId: '1:134783720891:web:610f893c59074c2f5a389e',
    messagingSenderId: '134783720891',
    projectId: 'fir-coneccion-1a529',
    authDomain: 'fir-coneccion-1a529.firebaseapp.com',
    storageBucket: 'fir-coneccion-1a529.firebasestorage.app',
  );
}
