# Generated by Django 6.0.5 on 2026-06-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpsDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economic_number', models.CharField(max_length=20, unique=True, verbose_name='Número Económico')),
                ('plates', models.CharField(max_length=20, unique=True, verbose_name='Placas')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está en ruta?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
